services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    env_file:
      - ./db/db.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: flask_container
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  pgdata:
